### ISSUE TITLE
TV tag generation fails

### ISSUE THREAD

**Issue by mueslo** [mueslo/pythonBits#105]
introduced in 958fbefdcb8750ca24d46371096d9d4af1a091d0

@znedw do you have time to fix this?

due to data structure mismatch: directors from IMDb are dicts with 'name' attribute, directors from TVDB are just strings

proposed solution: transform all 'people' into compatible format (i.e. in tvdb.py) or only add directors to tags for movies (reimplement _render_tags in MovieSubmission and add directors)

**Comment by znedw** [comment]
Fixed here (https://github.com/mueslo/pythonBits/pull/107)
@mueslo tested ok locally (with a tv show that was failing to tag prior).
