### ISSUE TITLE
Large screenshot files cause a 400 error on Imgur

### ISSUE THREAD

**Issue by Reverse256** [mueslo/pythonBits#118]
## **Description**

1) pb -b 4k.resolution.video.mp4
2) Go through the steps and imgur upload has a 400 Error

## **The Work Around**
1) Before confirming the submission, I can go to the directory with the screenshots
2) save them as a .jpg and rename it as the original .png filename so pythonbits will use it
3) enter y to confirm submission on pythonbits and upload works.

 - `pythonbits` version: 3.0.3

In my case, going from png to jpg made the file size go from 24M to 0.6M.

Manually uploading these .png files to imgur says it is too large.

## **Full log**
[pythonbits.log](https://github.com/mueslo/pythonBits/files/6035458/pythonbits.log)

**Comment by mueslo** [comment]
Imgur is not suitable for 4K screenshots precisely for this reason. Your workaround of lossy compression of screenshots is never the right approach (see rules).
