### ISSUE TITLE
Add option to modify infohash

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#18]
[mktor from pyroscope](https://github.com/pyroscope/pyrocore)

Has -X flag 

```
-X LABEL, --cross-seed=LABEL
                        set additional explicit label for cross-seeding
                        (changes info hash)
```

Standard should be `mktor -p -X [comment] [FILE] [announceUrl]`

**Comment by mueslo** [comment]
Just noticed that mktorrent already supports this (1.1 upwards, `-s` option) and is much more widely available than pyroscope's `mktor`
