### ISSUE TITLE
Exempt scene from encoding requirements (and add 'MPA1L2' mapping)

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#31]
Is there anyone I can fill in my own instead of the script dying :(

**Comment by mueslo** [comment]
That would be MP2, which isn't an accepted audio codec for any category AFAICT

**Comment by mueslo** [comment]
Should be done as part of #4

**Comment by mueslo** [comment]
Not sure if this is an issue still, closing for now
