### ISSUE TITLE
What to do about TV specials?

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#32]
For something like [this](https://www.thetvdb.com/index.php?tab=episode&seriesid=79302&seasonid=26744&id=4408653), is there any way of specifying anything that would get me to that result?

**Comment by mueslo** [comment]
I think TheTVDB uses Season 0 for Specials, so it should be S00E05. Then afterwards you should be able to modify the title before submitting if you think it should be some other episode number. Specials are a very big nuisance, especially for shows like Doctor Who :(

**Comment by eeeeeeeeeve** [comment]
You’re right! That worked perfectly ty!
