### ISSUE TITLE
Attempt to upload movie cover first?

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#35]
Given the high amount of errors with uploading movie posters, and given that the script errors out and you have you start all over again, is it possible to re-arrange the sequence so that the movie poster attempts to get uploaded first, so that you don't have 4 different clones of screenshots that get re-uploaded to imgur?

**Comment by mueslo** [comment]
This would require significant reworking of the underlying program structure to combat issues that are out of my control, not doing that, sorry :(
