### ISSUE TITLE
TVDB updated its API

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#37]
Errr TVDB API has issues...

**Comment by stevesbrain** [comment]
Hopefully https://github.com/dbr/tvdb_api/releases/tag/2.0 fixes it (I think we're on 1.9, which is a few years old)

**Comment by mueslo** [comment]
I'm currently not in the country (and won't be for another few weeks), so
feel free to submit any fixes

Steve Divskinsy <notifications@github.com> schrieb am Do., 3. Mai 2018,
14:14:

**Comment by mueslo** [comment]
What are the actual issues?

**Comment by eeeeeeeeeve** [comment]
No longer an issue! Seemed like a bug just that one day
