### ISSUE TITLE
Discrepancy between IMDB Stars and Full Cast tags, when alphabetically billed

### ISSUE THREAD

**Issue by project2502** [mueslo/pythonBits#53]
Saw generated description on the movie Choke 2008, https://www.imdb.com/title/tt1024715/

On IMDB, its stars are listed as: 
Stars: Sam Rockwell, Anjelica Huston, Kelly Macdonald

But because the cast tags are taken from the cast section, for Choke, it became:
Cast: Kathryn Alexander | Teodorina Bello | Kate Blumberg | Jonah Bobo | Willi Burke

For most films, no problem. Only a weird issue on films like Choke, where the "stars" is more useful information, and not the cast, as alphabetically/first billed. (Both cast, and starring are better aligned on wikipedia, https://en.wikipedia.org/wiki/Choke_(film).)

**Comment by mueslo** [comment]
Yep, this is a known issue. The IMDb API sadly doesn't expose the "Stars" ordering part.

**Comment by mueslo** [comment]
In the current version of `imdbpie`, stars can be found under get_title_auxiliary -> principals!

Alternatively, maybe switch to the `imdbpie.facade` API.
