### ISSUE TITLE
Imgur authorization yields "Unauthorized" error

### ISSUE THREAD

**Issue by plotski** [mueslo/pythonBits#58]
When running pythonBits for the first time, I'm adding my Imgur client ID and client secret, and then I'm prompted to go to `https://api.imgur.com/oauth2/authorize?client_id=MY_CLIENT_ID&response_type=pin`. On that page, I click on "allow" and I get the following JSON response:

```
{
  "data": {
    "error": "Unauthorized",
    "request": "/oauth2/authorize",
    "method": "POST"
  },
  "success": false,
  "status": 403
}
```

I've removed the client ID and created a new one, which didn't help.

**Comment by eeeeeeeeeve** [comment]
Are you logged in to Imgur when you go to the link?

**Comment by plotski** [comment]
Yes. If I'm not logged in, I get a login form instead of the "allow" button.

Can anyone reproduce this issue or is something peculiar going on?

**Comment by plotski** [comment]
This seems to have resolved itself. I just tried again and got the PIN by following the instructions, just as I did before.
