### ISSUE TITLE
Make console output more usable

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#6]
Results in:

`================================  screenshots  =================================
[u'https://i.imgur.com/fakelink.png', u'https://i.imgur.com/fakelink.png', u'https://i.imgur.com/fakelink.png', u'https://i.imgur.com/fakelink.png', u'https://i.imgur.com/fakelink.png']`

**Comment by mueslo** [comment]
That is expected, since `screenshots` is just a list of **u**nicode strings. Or is your issue that they are not easily copyable?

**Comment by eeeeeeeeeve** [comment]
Yup, mostly a "can't double click to select" issue :(
