### ISSUE TITLE
Exception: ('Unknown or unsupported audio codec', 'A_DTS')

### ISSUE THREAD

**Issue by plotski** [mueslo/pythonBits#60]
This should be easy to fix. I'm not sure what "A_DTS" means exactly, so I'll leave this to someone more knowledgeable.

Also, notice that the exception message is a tuple, not a string. Not sure if this is intentional or a remnant from Python 2.

**Comment by eeeeeeeeeve** [comment]
Is this because you're using `audio_track['codec_id']` instead of `audio_track['codec']` though?

**Comment by plotski** [comment]
No. The `audio_track` dictionary doesn't have the `codec` key for some reason.
Very likely because the output of my `mediainfo` binary doesn't have it either.
It has a `Codec ID` field instead, which is translated to `codec_id` by
pymediainfo.

It seems that for all of the videos I have that are labeled as "DTS" mediainfo
reports their Codec ID as "A_DTS" and their Format as "DTS".

What's your mediainfo version? I have 18.12.

**Comment by eeeeeeeeeve** [comment]
I somehow have MediaInfoLib - v0.7.82 :/

**Comment by plotski** [comment]
OK, that could be an explanation.

BTW, that version is from 2016.

https://github.com/MediaArea/MediaInfo/blob/master/History_GUI.txt

**Comment by plotski** [comment]
I've noticed that all audio codecs seem to start with "A_".

Am I the only one who's using a recent mediainfo version? Is this a Windows/Linux-related issue?

**Comment by tronje** [comment]
Having the exact same issue on Linux after also applying the workaround to fix #59. Is there any progress on this?

```
$ mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v19.09
```

**Comment by plotski** [comment]
It's fixed in my fork: https://github.com/plotski/pythonBits

I'm still waiting for @mueslo to merge: https://github.com/mueslo/pythonBits/pull/61

**Comment by tronje** [comment]
Seems to work like a charm, thanks! Though #61 does seem to be merged already...?

**Comment by plotski** [comment]
Yes, I was pointing to the discussion there. I've fixed lots of other issues.
