### ISSUE TITLE
Add support for ptpimg.me

### ISSUE THREAD

**Issue by dingho** [mueslo/pythonBits#66]
Feature Request
Imgur does not allow images over 20MB, which makes it unusable for most 4k screenshots.

**Comment by mueslo** [comment]
@znedw has partially implemented this https://github.com/znedw/pythonBits/commit/148bf5b977ab0466d39bb1e04fd36ca543fe3712

If he or someone else could make it a configurable switch in the settings it would be an instant merge :D

**Comment by znedw** [comment]
I'll get a PR in ASAP
