### ISSUE TITLE
Wrong title for TV episodes & architecture problem

### ISSUE THREAD

**Issue by mueslo** [mueslo/pythonBits#69]
1. Instead of "ShowName" the `title` field becomes "EpisodeName"  
likely cause: https://github.com/mueslo/pythonBits/commit/393f31280b3140fe99a6685200791194c5034705

2. Also, please remove any and all dependencies on `imdb` from the `tvdb` module. It does not belong there. I sadly missed this in the merge.

**Comment by plotski** [comment]
Should be fixed in the fix-episode-title branch.

BTW, I can't push to master:

```
Required status check "continuous-integration/travis-ci" is expected.
```

What does this mean?

**Comment by mueslo** [comment]
It means the build and tests need to complete successfully. Your branch looks like it is building fine though: https://travis-ci.org/github/mueslo/pythonBits/builds/694300758

Where did you see this error? Usually you get it on pull requests.

**Comment by plotski** [comment]
I just ran "git push". How do you push?

**Comment by mueslo** [comment]
Also git push. Did the trees diverge in any way, i.e. do you have a merge? In that case please do a rebase instead. If not, I currently don't know what the cause is.

But I think you can just perform a pull request and merge it if the status check completes.

**Comment by plotski** [comment]
I don't think so. I switched to master and ran "git pull", which worked fine. Then I
committed the fix for #69 and ran "git push".

Unfortunately, I lost the complete output. I'll get back to you if it happens again.

**Comment by mueslo** [comment]
I don't think it's the cause but usually it's better to do a `git pull --rebase` (or better yet, make it the global default with `git config --global pull.rebase true`).

**Comment by mueslo** [comment]
I've added this as a pull request https://github.com/mueslo/pythonBits/pull/71

Are you able to press the "rebase and merge" button?

**Comment by plotski** [comment]
Yup, that worked.
