### ISSUE TITLE
ptpimg option

### ISSUE THREAD

**Issue by dingho** [mueslo/pythonBits#72]
Question:  by default imgur is used for submitting screenshots.  How do you force ptpimg to be used instead?

**Comment by mueslo** [comment]
It isn't the default, because there is no default. It will ask you which one you want to use. I don't think you are running the development version?

**Comment by dingho** [comment]
I must not be on the development version. 
`pythonbits --version`  gives 3.0.2
and
`pip install pythonbits --upgrade`
shows everything is already up to date.

**Comment by mueslo** [comment]
try again now! just pushed 3.0.3

btw if you want to install the latest git commit, I think `pipx install git+https://github.com/mueslo/pythonbits.git@master` should work. Feel free to add that to the wiki!
