### ISSUE TITLE
Fails if no IMDb Rating

### ISSUE THREAD

**Issue by evo-33** [mueslo/pythonBits#9]
Found another bug, if there is no IMDb rating, it crashes. Probably more ideal to just not include the rating.

**Comment by mueslo** [comment]
Please post the exception or the link to an Imdb page where this happens so I can debug this

**Comment by evo-33** [comment]
http://www.imdb.com/title/tt6863494

**Comment by mueslo** [comment]
Should be fixed in 0eea4a07d8a4a913f75d615574103b9e94a04785
